"""add_agent_scores_table

Revision ID: 426b736263b8
Revises: 5f79c83bdc41
Create Date: 2026-06-10 16:58:09.934500

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "426b736263b8"
down_revision: str | Sequence[str] | None = "5f79c83bdc41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_listing_id", sa.Integer(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "scored_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_listing_id"],
            ["job_listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_listing_id", "agent_name", name="uq_listing_agent"),
    )
    op.create_index(
        "ix_agent_name_score", "agent_scores", ["agent_name", "score"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_name_score", table_name="agent_scores")
    op.drop_table("agent_scores")
    # ### end Alembic commands ###
