"""add workplace_type and contract_types columns

Revision ID: 5f79c83bdc41
Revises: 76a2e6d7dfed
Create Date: 2026-04-04 14:35:15.539101

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f79c83bdc41"
down_revision: str | Sequence[str] | None = "76a2e6d7dfed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_listings", sa.Column("workplace_type", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "job_listings",
        sa.Column("contract_types", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_listings", "contract_types")
    op.drop_column("job_listings", "workplace_type")
    # ### end Alembic commands ###
