"""initial tables

Revision ID: 76a2e6d7dfed
Revises:
Create Date: 2026-03-29 12:54:48.635364

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76a2e6d7dfed"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_listings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portal", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=False),
        sa.Column("location_raw", sa.String(length=500), nullable=True),
        sa.Column("salary_raw", sa.String(length=500), nullable=True),
        sa.Column("description_raw", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "scraped_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        "ix_company_title", "job_listings", ["company", "title"], unique=False
    )
    op.create_index("ix_content_hash", "job_listings", ["content_hash"], unique=False)
    op.create_index(
        "ix_portal_scraped", "job_listings", ["portal", "scraped_at"], unique=False
    )
    op.create_table(
        "scraping_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portal", sa.String(length=50), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("listings_found", sa.Integer(), nullable=False),
        sa.Column("listings_new", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scraping_runs")
    op.drop_index("ix_portal_scraped", table_name="job_listings")
    op.drop_index("ix_content_hash", table_name="job_listings")
    op.drop_index("ix_company_title", table_name="job_listings")
    op.drop_table("job_listings")
    # ### end Alembic commands ###
